package sgpc.domain;
// Generated 23/11/2016 03:44:08 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dadosconsolidados generated by hbm2java
 */
@Entity
@Table(name = "dadosconsolidados", catalog = "sgpc")
public class Dadosconsolidados implements java.io.Serializable {

	private Integer numProcesso;
	private Area area;
	private Fornecedor fornecedor;
	private Status status;
	private Tipocontrato tipocontrato;
	private String tipoDado;
	private String numContrato;
	private String descServico;
	private Double vlPropostaIni;
	private Double vlPropostaFim;
	private String analistaResp;
	private Set cronogramas = new HashSet(0);

	public Dadosconsolidados() {
	}

	public Dadosconsolidados(Area area, Fornecedor fornecedor, Status status, Tipocontrato tipocontrato) {
		this.area = area;
		this.fornecedor = fornecedor;
		this.status = status;
		this.tipocontrato = tipocontrato;
	}

	public Dadosconsolidados(Area area, Fornecedor fornecedor, Status status, Tipocontrato tipocontrato,
			String tipoDado, String numContrato, String descServico, Double vlPropostaIni, Double vlPropostaFim,
			String analistaResp, Set cronogramas) {
		this.area = area;
		this.fornecedor = fornecedor;
		this.status = status;
		this.tipocontrato = tipocontrato;
		this.tipoDado = tipoDado;
		this.numContrato = numContrato;
		this.descServico = descServico;
		this.vlPropostaIni = vlPropostaIni;
		this.vlPropostaFim = vlPropostaFim;
		this.analistaResp = analistaResp;
		this.cronogramas = cronogramas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "numProcesso", unique = true, nullable = false)
	public Integer getNumProcesso() {
		return this.numProcesso;
	}

	public void setNumProcesso(Integer numProcesso) {
		this.numProcesso = numProcesso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idArea", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFornecedor", nullable = false)
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idStatus", nullable = false)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoContrato", nullable = false)
	public Tipocontrato getTipocontrato() {
		return this.tipocontrato;
	}

	public void setTipocontrato(Tipocontrato tipocontrato) {
		this.tipocontrato = tipocontrato;
	}

	@Column(name = "TipoDado", length = 2)
	public String getTipoDado() {
		return this.tipoDado;
	}

	public void setTipoDado(String tipoDado) {
		this.tipoDado = tipoDado;
	}

	@Column(name = "NumContrato", length = 45)
	public String getNumContrato() {
		return this.numContrato;
	}

	public void setNumContrato(String numContrato) {
		this.numContrato = numContrato;
	}

	@Column(name = "DescServico", length = 100)
	public String getDescServico() {
		return this.descServico;
	}

	public void setDescServico(String descServico) {
		this.descServico = descServico;
	}

	@Column(name = "VlPropostaIni", precision = 22, scale = 0)
	public Double getVlPropostaIni() {
		return this.vlPropostaIni;
	}

	public void setVlPropostaIni(Double vlPropostaIni) {
		this.vlPropostaIni = vlPropostaIni;
	}

	@Column(name = "VlPropostaFim", precision = 22, scale = 0)
	public Double getVlPropostaFim() {
		return this.vlPropostaFim;
	}

	public void setVlPropostaFim(Double vlPropostaFim) {
		this.vlPropostaFim = vlPropostaFim;
	}

	@Column(name = "AnalistaResp", length = 80)
	public String getAnalistaResp() {
		return this.analistaResp;
	}

	public void setAnalistaResp(String analistaResp) {
		this.analistaResp = analistaResp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dadosconsolidados")
	public Set getCronogramas() {
		return this.cronogramas;
	}

	public void setCronogramas(Set cronogramas) {
		this.cronogramas = cronogramas;
	}

}
