package sgpc.domain;
// Generated 23/11/2016 03:44:08 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fornecedor generated by hbm2java
 */
@Entity
@Table(name = "fornecedor", catalog = "sgpc")
public class Fornecedor implements java.io.Serializable {

	private Integer idFornecedor;
	private String descricao;
	private Integer cnpj;
	private Set dadosconsolidadoses = new HashSet(0);

	public Fornecedor() {
	}

	public Fornecedor(String descricao, Integer cnpj, Set dadosconsolidadoses) {
		this.descricao = descricao;
		this.cnpj = cnpj;
		this.dadosconsolidadoses = dadosconsolidadoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idFornecedor", unique = true, nullable = false)
	public Integer getIdFornecedor() {
		return this.idFornecedor;
	}

	public void setIdFornecedor(Integer idFornecedor) {
		this.idFornecedor = idFornecedor;
	}

	@Column(name = "Descricao", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "Cnpj")
	public Integer getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(Integer cnpj) {
		this.cnpj = cnpj;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fornecedor")
	public Set getDadosconsolidadoses() {
		return this.dadosconsolidadoses;
	}

	public void setDadosconsolidadoses(Set dadosconsolidadoses) {
		this.dadosconsolidadoses = dadosconsolidadoses;
	}

}
