package sgpc.domain;
// Generated 23/11/2016 16:31:09 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoUsuario generated by hbm2java
 */
@Entity
@Table(name = "tipo_usuario", catalog = "sgpc")
public class TipoUsuario implements java.io.Serializable {

	private String tipo;
	private String descricao;
	private Set usuarios = new HashSet(0);

	public TipoUsuario() {
	}

	public TipoUsuario(String tipo) {
		this.tipo = tipo;
	}

	public TipoUsuario(String tipo, String descricao, Set usuarios) {
		this.tipo = tipo;
		this.descricao = descricao;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "tipo", unique = true, nullable = false, length = 15)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "descricao", length = 30)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUsuario")
	public Set getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set usuarios) {
		this.usuarios = usuarios;
	}

}
