package sgpc.domain;
// Generated 23/11/2016 03:44:08 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipocontrato generated by hbm2java
 */
@Entity
@Table(name = "tipocontrato", catalog = "sgpc")
public class Tipocontrato implements java.io.Serializable {

	private Integer idTipoContrato;
	private String descricao;
	private Set dadosconsolidadoses = new HashSet(0);

	public Tipocontrato() {
	}

	public Tipocontrato(String descricao, Set dadosconsolidadoses) {
		this.descricao = descricao;
		this.dadosconsolidadoses = dadosconsolidadoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoContrato", unique = true, nullable = false)
	public Integer getIdTipoContrato() {
		return this.idTipoContrato;
	}

	public void setIdTipoContrato(Integer idTipoContrato) {
		this.idTipoContrato = idTipoContrato;
	}

	@Column(name = "Descricao", length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipocontrato")
	public Set getDadosconsolidadoses() {
		return this.dadosconsolidadoses;
	}

	public void setDadosconsolidadoses(Set dadosconsolidadoses) {
		this.dadosconsolidadoses = dadosconsolidadoses;
	}

}
