package sgpc.domain;
// Generated 23/11/2016 03:44:08 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tmp generated by hbm2java
 */
@Entity
@Table(name = "tmp", catalog = "sgpc")
public class Tmp implements java.io.Serializable {

	private Integer idTmp;
	private String descricao;
	private Set cronogramas = new HashSet(0);

	public Tmp() {
	}

	public Tmp(String descricao, Set cronogramas) {
		this.descricao = descricao;
		this.cronogramas = cronogramas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTMP", unique = true, nullable = false)
	public Integer getIdTmp() {
		return this.idTmp;
	}

	public void setIdTmp(Integer idTmp) {
		this.idTmp = idTmp;
	}

	@Column(name = "Descricao", length = 60)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmp")
	public Set getCronogramas() {
		return this.cronogramas;
	}

	public void setCronogramas(Set cronogramas) {
		this.cronogramas = cronogramas;
	}

}
