package sgpc.domain;
// Generated 23/11/2016 16:31:09 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "sgpc")
public class Usuario implements java.io.Serializable {
	
	public static final String TIPO_ADMINISTRADOR = "ADMINISTRADOR";
	public static final String TIPO_FUNCIONARIO = "FUNCIONARIO";
	public static final String TIPO_CONVIDADO = "CONVIDADO";
	  
	public static final byte ADMINISTRADOR = 0;
	public static final byte FUNCIONARIO = 1;
	public static final byte CONVIDADO = 2;
	  
	public static final byte INATIVO = 0;
	public static final byte ATIVO = 1;
	  
	private UsuarioId id;
	private TipoUsuario tipoUsuario;
	private String email;
	private byte status;

	public Usuario() {
	}

	public Usuario(UsuarioId id, TipoUsuario tipoUsuario, byte status) {
		this.id = id;
		this.tipoUsuario = tipoUsuario;
		this.status = status;
	}

	public Usuario(UsuarioId id, TipoUsuario tipoUsuario, String email, byte status) {
		this.id = id;
		this.tipoUsuario = tipoUsuario;
		this.email = email;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 20)),
			@AttributeOverride(name = "senha", column = @Column(name = "senha", nullable = false, length = 20)) })
	public UsuarioId getId() {
		return this.id;
	}

	public void setId(UsuarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo", nullable = false)
	public TipoUsuario getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}
	
	  public String getTipo_Adm() {
		    return TIPO_ADMINISTRADOR;
		  }
	  
	  public String getTipo_Func() {
		    return TIPO_FUNCIONARIO;
		  }
	  
	  public String getTipo_Con() {
		    return TIPO_CONVIDADO;
		  }

	  public byte getTipo_AdmB() {
		    return ADMINISTRADOR;
		  }

	public byte getTipo_FuncB() {
		    return FUNCIONARIO;
		  }

	public byte getTipo_ConB() {
		    return CONVIDADO;
		  }  
}
